### ISSUE TITLE
Create report function doesn't work

### ISSUE THREAD

**Issue by tbeckiesms** [jaymegordo/SMSEventLog#106]
- 

<details>
<summary>Traceback
</summary>
<p>

Paste error text here:
Traceback (most recent call last):
  File "smseventlog\gui\tables.py", line 3024, in create_report
ModuleNotFoundError: No module named 'smseventlog.gui.refreshtables' 
```pytb


```
</p>
</details>

**Comment by jaymegordo** [comment]
Which report?

**Comment by tbeckiesms** [comment]
Availability report
