### ISSUE TITLE
Component SMR Tab Missing Headers in 3.7.12

### ISSUE THREAD

**Issue by tbeckiesms** [jaymegordo/SMSEventLog#116]
The headers on the Component SMR tab are missing on the latest EL tab. 

- 

<details>
<summary>Traceback
</summary>
<p>

```pytb
<!-- Paste error text here: -->


```
</p>
</details>

**Comment by tbeckiesms** [comment]
![image](https://user-images.githubusercontent.com/102313875/183103685-e563942d-2497-4765-b051-1c42c5d4cda8.png)

**Comment by jaymegordo** [comment]
I was having this too, it's cause underlying QT version was updated and messed with the header state. May happen on other tables too.

Try doing table > reset column layout, close and re open EL

**Comment by tbeckiesms** [comment]
Ah ya that seems to work you can close this
