### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by rosie1018** [jaymegordo/SMSEventLog#117]
- 

<details>
<summary>Traceback
</summary>
<p>

```pytb
<!-- Paste error text here: -->


```
</p>
</details>

**Comment by jaymegordo** [comment]
What is the bug?

**Comment by rosie1018** [comment]
Also is there a issue with the event log I cant jump to event log from the work orders  is there a update?



Robert Mills
Supervisor, Field / Superviseur routier

Équipement SMS / SMS Equipment Inc.
Wabush
Phone: 709-282-3777 x2404
Cell: 709-987-0273

**Comment by jaymegordo** [comment]
Not sure what this issue was, please open a new issue if it's still happening
