### ISSUE TITLE
Couldn't Run Function : headerData

### ISSUE THREAD

**Issue by SMSDon** [jaymegordo/SMSEventLog#118]
![Error Log](https://user-images.githubusercontent.com/110925380/183706035-cd42f04c-e1b1-433c-93bb-a7b8c9642fde.JPG)

<details>
<summary>Traceback
</summary>
<p>

```pytb
<!-- Paste error text here: -->


```
</p>
</details>

**Comment by jaymegordo** [comment]
@SMSDon Try and do `Table > Reset Column Layout` then refresh the table again, let me know if that works. 

The last update changed the column layout so your local header settings might have got a bit messed up.
