### ISSUE TITLE
Multithread Error - create_word

### ISSUE THREAD

**Issue by SMSDon** [jaymegordo/SMSEventLog#119]
- 

![Vibrating Bearing](https://user-images.githubusercontent.com/110925380/183708685-6e98eecd-08b0-442d-8127-67c916a4a3bb.JPG)
<details>
<summary>Traceback
</summary>
<p>

```pytb
<!-- Paste error text here: -->


```
</p>
</details>

**Comment by jaymegordo** [comment]
@SMSDon can you please attach the traceback text so I can see the error details? Use the `Copy Text` button in the error dialog.

**Comment by jaymegordo** [comment]
@SMSDon didn't get more info so I'm going to close this for now, but please open again and add more info if its still happening
