### ISSUE TITLE
can not add unit

### ISSUE THREAD

**Issue by rosie1018** [jaymegordo/SMSEventLog#122]
When trying to add a new unit i keep getting a Database transaction error.

reset event log and data base connection and still did not work 

BTW this is Simone writing this for Robert

- 

<details>
<summary>Traceback
</summary>
<p>

```pytb
<!-- Replace this line and paste error text in this section: -->

```
</p>
</details>

**Comment by jaymegordo** [comment]
Fixed in 3.7.14
