### ISSUE TITLE
Adding new unit and minesite

### ISSUE THREAD

**Issue by farahmad** [jaymegordo/SMSEventLog#77]
- 

<details>
<summary>Traceback
</summary>
<p>

Paste error text here:
```pytb


```
</p>
</details>

**Comment by jaymegordo** [comment]
`Unit Number` is currently the only unique ID in the database table
- [ ] Make combination UID eg unit + serial number/minesite

**Comment by jaymegordo** [comment]
Won't be able to fix this, unique unit is important in too many places
